name: Build Unreal Engine Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Git LFS
      run: |
        git lfs install
        git lfs pull

    - name: Build, Cook, Stage & Package UE Project
      run: |
        & "E:/Unreal Editors/UE_5.3/Engine/Build/BatchFiles/RunUAT.bat" BuildCookRun -nop4 -utf8output -nocompileeditor -skipbuildeditor -cook -project="${{ github.workspace }}/GGJ2025.uproject" -platform=Win64 -installed -stage -archive -package -build -pak -iostore -compressed -prereqs -archivedirectory="E:/Work/Projects/GGJ-2025/Build/Archive" -clientconfig=Development" -nocompile -nocompileuat
