name: Build Unreal Engine Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    name: Build Unreal Engine Project

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Git LFS
      run: |
        git lfs install
        git lfs pull

    - name: Build, Cook, Stage & Package UE Project
      env:
        UAT_PATH: 'E:/Unreal Editors/UE_5.3/Engine/Build/BatchFiles/RunUAT.bat'
        PROJECT_PATH: 'E:\Work\Projects\GGJ-2025\GGJ2025.uproject'
        OUTPUT_PATH: 'E:\Work\Projects\GGJ-2025\Build\Archive'
      run: |
        & "$env:UAT_PATH" BuildCookRun -project="$env:PROJECT_PATH" -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development -cook -allmaps -build -stage -pak -archive -archivedirectory="$env:OUTPUT_PATH"
